# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(verbose_name=16)),
                ('live', models.IntegerField(verbose_name=8)),
                ('name', models.CharField(max_length=512)),
                ('name_sh', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=16)),
                ('kind_sport', models.CharField(max_length=32)),
                ('prize_amount', models.CharField(max_length=64)),
                ('prize_currency', models.CharField(max_length=32)),
                ('itfid', models.CharField(max_length=64)),
                ('itfname', models.CharField(max_length=64)),
                ('ground_id', models.CharField(max_length=8)),
                ('ground_name', models.CharField(max_length=32)),
                ('ground_mainid', models.CharField(max_length=8)),
                ('ground_main', models.CharField(max_length=8)),
            ],
        ),
    ]
